### ISSUE TITLE
UTF-32 validator

### ISSUE THREAD

**Issue by lemire** [simdutf/simdutf#113]
We should have a function to validate UTF-32 inputs.

cc @NicolasJiaxin

**Comment by NicolasJiaxin** [comment]
@lemire I have started to work on the vectorized validation, but I am not sure exactly how to proceed. The two requirements are
1. No word is larger than 10FFFF.
2. No word is in the range D800 to DFFF.

1 implies that the 11 most significant bits of a 32-bit word must be 0. We can easily check for that using a running or like in ASCII validation. But that is not sufficient to check for 1 (0x00110000 is not valid but 11 most significant bits are 0). I think one way to do it would be to isolate the second most significant byte and somehow check that it is less than 10.
For 2, I think we could first identify words with only 2 low bytes (of the form 0x0000XXXX) and then check if these words are in the range D800 to DFFF or not (maybe using a small lookup table depending on where those words are?). 
Do you have any suggestions or any idea for another way to do it?

**Comment by lemire** [comment]
Yes. I gave a little bit of thought to the problem. It is a fun one!!!

**Comment by lemire** [comment]
Ok. Regarding the maximum, we can just do something like this...

```C++
currentmax = _mm_max_epu32(input,currentmax);
```

or 


```C++
currentmax = _mm256_max_epu32(input,currentmax);
```


You start with 
```C++
currentmax = _mm_setzero_si128() 
```
or
```C++
currentmax = _mm256_setzero_si256() 
```

And then, once you ran through all of the data, you can just do...

```
standardmax = _mm_set1_epi32(0x10FFFF);
_mm_xor_si128(_mm_max_epu16(currentmax, _mm_set1_epi32(standardmax)), standardmax);
```
(or the AVX equivalent)

And the result should be all zeroes if and only if we never exceed 0x10FFFF. So that part should be stupidly fast. I think you can do the same thing with our higher-level API.

My point is that checking that the maximum is not larger than 0x10FFFF is very cheap and easy.

**Comment by NicolasJiaxin** [comment]
Ok thanks! I will try that, that was the part I found troublesome. I think I have an idea for the other parts.

**Comment by lemire** [comment]
There are many ways to solve part 2. One way is to 
```
offset = _mm_set1_epi32(0xffff2000);
...
currentoffsetmax = _mm_max_epu32(_mm_add_epi32(input, offset), currentoffsetmax);
```

And check that the result is no larger than 0xfffff7ff.

```
standardoffsetmax = _mm_set1_epi32(0xfffff7ff);
_mm_xor_si128(_mm_max_epu16(currentoffsetmax, standardoffsetmax), standardoffsetmax);
```

This should be zero if the value is never in the forbidden range.

This is 2 instructions per input (_mm_max_epu32 and _mm_add_epi32). I think it is going to be hard to do better.

If you add these 2 instructions to the 1 instruction for the maximum, you are at 3 instructions per input, plus a load instruction. So four instruction per SIMD register loaded. That should be really fast.

**Comment by lemire** [comment]
For ARM, you can do something similar.
