### ISSUE TITLE
Build fast one-pass "detect encoding function"

### ISSUE THREAD

**Issue by lemire** [simdutf/simdutf#124]
Currently we might do something like this...

```C++
simdutf_warn_unused encoding_type implementation::autodetect_encoding(const char * input, size_t length) const noexcept {
    // If there is a BOM, then we trust it.
    auto bom_encoding = simdutf::BOM::check_bom(input, length);
    if(bom_encoding != encoding_type::unspecified) { return bom_encoding; }
    // UTF8 is common, it includes ASCII, and is commonly represented
    // without a BOM, so if it fits, go with that. Note that it is still
    // possible to get it wrong, we are only 'guessing'. If some has UTF-16
    // data without a BOM, it could pass as UTF-8.
    //
    // An interesting twist might be to check for UTF-16 ASCII first (every
    // other byte is zero).
    if(validate_utf8(input, length)) { return encoding_type::UTF8; }
    // The next most common encoding that might appear without BOM is probably
    // UTF-16LE, so try that next.
    if((length % 2) == 0) {
      if(validate_utf16(reinterpret_cast<const char16_t*>(input), length/2)) { return encoding_type::UTF16_LE; }
    }
    if((length % 4) == 0) {
      if(validate_utf32(reinterpret_cast<const char32_t*>(input), length/4)) { return encoding_type::UTF32_LE; }
    }
    return encoding_type::unspecified;
}
```

It would not normally be so bad, but our SIMD `validate_utf*` functions are optimistic: they expect the input to be valid and so they always scan the whole input. If the input is UTF-8, it is pretty good...  We could use our fallback functions instead... 

Importantly, the 'answer' is not well defined. What we would like is a function that returns which unicode types are *possible* given the input. So the result is an enumeration... utf8, utf16_le, utf16_be, utf32_le, utf32_be....?

But it seems that there ought to be a one-pass algorithm to detect the unicode type... So you scan the input, using a single pass, and when you are done, you know exactly which types are allowed.

**Comment by lemire** [comment]
@NicolasJiaxin Want to take a stab at it?

**Comment by NicolasJiaxin** [comment]
Yes of course. This looks interesting.
