### ISSUE TITLE
Relatively poor performance of validate_utf16 on ARM (Apple M1) for pure emoji

### ISSUE THREAD

**Issue by lemire** [simdutf/simdutf#136]
Using Apple M1 and clang 12, I am getting that the accelerated validate_utf16 function is *slower* than our scalar fallback on the `Emoji-Lipsum.utf16.txt` test file (pure emoji).

```
❯  ./build/benchmarks/benchmark -F unicode_lipsum/lipsum/Emoji-Lipsum.utf16.txt -P validate_utf16
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 69.1
testcases: 1
input detected as UTF16 little-endian
current system detected as arm64
===========================
validate_utf16+arm64, input size: 65542, iterations: 2000, dataset: unicode_lipsum/lipsum/Emoji-Lipsum.utf16.txt
kpc_set_config failed, run the program with sudo
   1.873 GB/s (7.2 %)    0.936 Gc/s     2.00 byte/char 
validate_utf16+fallback, input size: 65542, iterations: 2000, dataset: unicode_lipsum/lipsum/Emoji-Lipsum.utf16.txt
   2.579 GB/s (3.4 %)    1.289 Gc/s     2.00 byte/char 
```

So we are nearly 40% slower with the accelerated function than the fallback function.

But not on x64 (AMD Rome, GCC 12)...

```
$ ./build/benchmarks/benchmark -F unicode_lipsum/lipsum/Emoji-Lipsum.utf16.txt -P validate_utf16
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 67.1
testcases: 1
input detected as UTF16 little-endian
current system detected as haswell
===========================
validate_utf16+fallback, input size: 65542, iterations: 2000, dataset: unicode_lipsum/lipsum/Emoji-Lipsum.utf16.txt
   9.507 ins/byte,    9.507 cycle/byte,    2.025 GB/s (0.8 %),     3.405 GHz,    5.654 ins/cycle
  19.012 ins/char,   19.012 cycle/char,    1.013 Gc/s (0.8 %)     2.00 byte/char
validate_utf16+haswell, input size: 65542, iterations: 2000, dataset: unicode_lipsum/lipsum/Emoji-Lipsum.utf16.txt
   1.071 ins/byte,    1.071 cycle/byte,   12.343 GB/s (1.9 %),     3.466 GHz,    3.814 ins/cycle
   2.142 ins/char,    2.142 cycle/char,    6.172 Gc/s (1.9 %)     2.00 byte/char
validate_utf16+westmere, input size: 65542, iterations: 2000, dataset: unicode_lipsum/lipsum/Emoji-Lipsum.utf16.txt
   1.825 ins/byte,    1.825 cycle/byte,    8.915 GB/s (3.2 %),     3.449 GHz,    4.717 ins/cycle
   3.649 ins/char,    3.649 cycle/char,    4.458 Gc/s (3.2 %)     2.00 byte/char
```

The relevant ARM code is as follows:

```C++
const char16_t* arm_validate_utf16le(const char16_t* input, size_t size) {
    const char16_t* end = input + size;
    const auto v_d8 = simd8<uint8_t>::splat(0xd8);
    const auto v_f8 = simd8<uint8_t>::splat(0xf8);
    const auto v_fc = simd8<uint8_t>::splat(0xfc);
    const auto v_dc = simd8<uint8_t>::splat(0xdc);
    while (input + 16 < end) {
        // 0. Load data: since the validation takes into account only higher
        //    byte of each word, we compress the two vectors into one which
        //    consists only the higher bytes.
        const auto in0 = simd16<uint16_t>(input);
        const auto in1 = simd16<uint16_t>(input + simd16<uint16_t>::SIZE / sizeof(char16_t));
        const auto t0 = in0.shr<8>();
        const auto t1 = in1.shr<8>();
        const simd8<uint8_t> in = simd16<uint16_t>::pack(t0, t1);
        // 1. Check whether we have any 0xD800..DFFF word (0b1101'1xxx'yyyy'yyyy).
        const auto surrogates_wordmask = ((in & v_f8) == v_d8);
        if(surrogates_wordmask.none()) {
// We never come here
             input += 16;
        } else {
/*****
We keep coming here 
****/
             const auto vH = simd8<uint8_t>((in & v_fc) ==  v_dc);
            const auto vL = simd8<uint8_t>(surrogates_wordmask).bit_andnot(vH);
            // We are going to need these later:
            const uint8_t low_vh = vH.first();
            const uint8_t high_vl = vL.last();
            // We shift vH down, possibly killing low_vh
            const auto sh = simd8<uint8_t>({1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,0xFF});
            const auto vHshifteddown = vH.apply_lookup_16_to(sh);
            const auto match = vHshifteddown == vL;
            // We need to handle the fact that high_vl is unmatched.
            // We could use this...
            // const uint8x16_t allbutlast = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0xFF};
            //             match = vorrq_u8(match, allbutlast);
            // but sh will do:
            const auto fmatch = simd8<bool>(simd8<uint8_t>(match) | sh);
            // We deliberately take these two lines out of the following branchy code
            // so that they are always s
            if (fmatch.all() && low_vh == 0) {
                input += (high_vl == 0) ? 16 : 15;
            } else {
                return nullptr;
            }
        }
    }
    return input;
}

```

**Comment by clausecker** [comment]
Is the amd64 code the one I wrote?  Doesn't look like it.  I can port it to ARM64 real quick if you want to check the performance.

**Comment by lemire** [comment]
> Is the amd64 code the one I wrote? 

No. It is older code.

**Comment by clausecker** [comment]
Here's my code for comparison: [validation_avx512.S](https://github.com/simdutf/simdutf/blob/07785c316ccb3072f55ebef578e7c9bffbed05f1/validation_avx512.S)

It does a bit more than your code in that it checks for all the following classes of errors:

 - uncharacters of the form `U+XFFFE` and `U+XFFFF` for `X = 0 .. 10`
 - uncharacters in the range `U+FDD0` to `U+FDEF`
 - lone or unmatched surrogates

I'm not sure if your code actually checks for all of these.  On your icelake box, I get the following performance figures for the lipsum benchmark sets:

```
name                                                       speed
Avx512/../unicode_lipsum/lipsum/Arabic-Lipsum.utf16.txt      1.81µs ± 0%
Avx512/../unicode_lipsum/lipsum/Chinese-Lipsum.utf16.txt      475ns ± 2%
Avx512/../unicode_lipsum/lipsum/Emoji-Lipsum.utf16.txt       3.94µs ± 0%
Avx512/../unicode_lipsum/lipsum/Hebrew-Lipsum.utf16.txt      1.48µs ± 0%
Avx512/../unicode_lipsum/lipsum/Hindi-Lipsum.utf16.txt       1.30µs ± 0%
Avx512/../unicode_lipsum/lipsum/Japanese-Lipsum.utf16.txt     474ns ± 2%
Avx512/../unicode_lipsum/lipsum/Korean-Lipsum.utf16.txt      1.08µs ± 0%
Avx512/../unicode_lipsum/lipsum/Latin-Lipsum.utf16.txt       3.44µs ± 0%
Avx512/../unicode_lipsum/lipsum/Russian-Lipsum.utf16.txt     2.30µs ± 0%
Avx512/../unicode_lipsum/lipsum/Arabic-Lipsum.utf16.txt    50.5GB/s ± 0%
Avx512/../unicode_lipsum/lipsum/Chinese-Lipsum.utf16.txt   98.7GB/s ± 2%
Avx512/../unicode_lipsum/lipsum/Emoji-Lipsum.utf16.txt     16.6GB/s ± 0%
Avx512/../unicode_lipsum/lipsum/Hebrew-Lipsum.utf16.txt    50.5GB/s ± 0%
Avx512/../unicode_lipsum/lipsum/Hindi-Lipsum.utf16.txt     50.5GB/s ± 0%
Avx512/../unicode_lipsum/lipsum/Japanese-Lipsum.utf16.txt  98.7GB/s ± 2%
Avx512/../unicode_lipsum/lipsum/Korean-Lipsum.utf16.txt    50.4GB/s ± 0%
Avx512/../unicode_lipsum/lipsum/Latin-Lipsum.utf16.txt     50.6GB/s ± 0%
Avx512/../unicode_lipsum/lipsum/Russian-Lipsum.utf16.txt   50.5GB/s ± 0%
```

Note that this is AVX-512, not AVX-2.  However, I do not use any AVX-512 features that wouldn't be easy to emulate with AVX2.  So for fairness, divide the speed by 2 to get an estimate for the AVX2 performance of a similar AVX2 validation kernel.

**Comment by lemire** [comment]
@clausecker 

It is likely that your code is much faster.

**Comment by lemire** [comment]
(Note that the issue has to do with ARM NEON. It does not invalidate the belief that your algo. is superior. We need to investigate.)

**Comment by lemire** [comment]
We definitively should match

> lone or unmatched surrogates


Regarding noncharacters, I am not convinced we should reject them outright... Here is what wikipedia says...

<img width="1214" alt="Screen Shot 2022-06-30 at 6 26 17 PM" src="https://user-images.githubusercontent.com/391987/176788977-75ac8ab8-a4f9-43b8-a56c-9de920bc2fad.png">

Here is what the current FAQ says...

> The formal wording of the definition of "noncharacter" in the standard has always indicated that noncharacters "should never be interchanged." That led some people to assume that the definition actually meant "shall not be interchanged" and that therefore the presence of a noncharacter in any Unicode string immediately rendered that string malformed according to the standard. But the intended use of noncharacters requires the ability to exchange them in a limited context, at least across APIs and even through data files and other means of "interchange", so that they can be processed as intended. The choice of the word "should" in the original definition was deliberate, and indicated that one should not try to interchange noncharacters precisely because their interpretation is strictly internal to whatever implementation uses them, so they have no publicly interchangeable semantics. But other informative wording in the text of the core specification and in the character names list was differently and more strongly worded, leading to contradictory interpretations. Given this ambiguity of intent, in 2013 the UTC issued [Corrigendum #9](http://www.unicode.org/versions/corrigendum9.html), which deleted the phrase "and that should never be interchanged" from the definition of noncharacters, to make it clear that prohibition from interchange is not part of the formal definition of noncharacters. Corrigendum #9 has been incorporated into the core specification for Unicode 7.0.

Thus noncharacter *may* be interchanged and should not be prohibited.

**Comment by lemire** [comment]
> **Are noncharacters invalid in Unicode strings and UTFs?**
> Absolutely not. Noncharacters do not cause a Unicode string to be ill-formed in any UTF. This can be seen explicitly in the [table above](https://www.unicode.org/faq/private_use.html#nonchar_codes), where every noncharacter code point has a well-formed representation in UTF-32, in UTF-16, and in UTF-8. An implementation which converts noncharacter code points between one UTF representation and another must preserve these values correctly. The fact that they are called "noncharacters" and are not intended for open interchange does not mean that they are somehow illegal or invalid code points which make strings containing them invalid.

**Comment by lemire** [comment]
Please refer to https://www.unicode.org/faq/private_use.html

**Comment by clausecker** [comment]
Okay, I'll go ahead and take out all these checks.  Will make the code somewhat faster and easier to understand, too.

**Comment by clausecker** [comment]
@lemire It may be possible to use preprocessor conditionals to produce various variants of the code.  I think e.g. a variant that replaces these with `U+FFFD` will also be useful.

**Comment by lemire** [comment]
>  use preprocessor conditionals

The C++ way would be to use a template. 

Or use scripts (the Go way!!!).

**Comment by lemire** [comment]
@danlark1 figured out the issue, the call to `none()` is ridiculously expensive under NEON. Switching to something else made the problem go away.
