### ISSUE TITLE
AVX-512 autodetect_encodings

### ISSUE THREAD

**Issue by lemire** [simdutf/simdutf#141]
We need to implement autodetect_encodings using AVX-512, after merging https://github.com/simdutf/simdutf/pull/134

**Comment by lemire** [comment]
@NicolasJiaxin I expect that you can probably 'take a stab' at this... even though I think that we will be able to build on @clausecker's work regarding UTF-16 validation.

**Comment by clausecker** [comment]
I've improved the validation code further.  Will try to push a change with the simplified code soon.  The new validation only checks for mismatched surrogates (and does so FAST).

**Comment by lemire** [comment]
> and does so FAST

Proof needed. 

:-)

**Comment by NicolasJiaxin** [comment]
@lemire Sure! I am trying to solve #129. I think I should be able to get it working soon hopefully...
