### ISSUE TITLE
create C API

### ISSUE THREAD

**Issue by lemire** [simdutf/simdutf#162]
It might be interesting to create a C API or to at least ensure that the library is callable from C.

Our public API is effectively very close to C.

**Comment by lemire** [comment]
Related: https://github.com/simdutf/simdutf/issues/158

**Comment by lemire** [comment]
We will not be doing this. It is more complicated than expected and ultimately, unnecessary. 

An interested user could write a C wrapper.

**Comment by Nugine** [comment]
For anyone looking for a C wrapper: 
There is [a generated wrapper](https://github.com/Nugine/simdutf-rs/blob/a1fc58c2def9b5191e28f908abdbb0e2a086b875/crates/simdutf/cpp/simdutfrs.cpp) in my [Rust binding repository](https://github.com/Nugine/simdutf-rs).

**Comment by lemire** [comment]
@Nugine Well well… that is interesting. Could we bring this back in the main repo?

**Comment by Nugine** [comment]
> @Nugine Well well… that is interesting. Could we bring this back in the main repo?

It's easy to write a similar generator in Python or C++. The Rust version is [here](https://github.com/Nugine/simdutf-rs/blob/a1fc58c2def9b5191e28f908abdbb0e2a086b875/codegen/src/bindings.rs#L6-L80).
