### ISSUE TITLE
License of ConvertUTF.cpp and ConvertUTF.h

### ISSUE THREAD

**Issue by bkmgit** [simdutf/simdutf#170]
The files [ConvertUTF.h](https://github.com/simdutf/simdutf/blob/master/benchmarks/competition/llvm/ConvertUTF.h) and [ConvertUTF.cpp](https://github.com/simdutf/simdutf/blob/master/benchmarks/competition/llvm/ConvertUTF.cpp) seem to be under non free licenses.  The LLVM project has updated them, see [here](https://github.com/llvm/llvm-project/issues/32309), with [ConvertUTF.h from breakpad](https://raw.githubusercontent.com/google/breakpad/master/src/common/convert_UTF.h) and [ConvertUTF.cc also from breakpad](https://raw.githubusercontent.com/google/breakpad/master/src/common/convert_UTF.cc). As indicated at https://github.com/AmokHuginnsson/replxx/issues/12, they can also be replaced by https://github.com/nemtrif/utfcpp

**Comment by lemire** [comment]
These files are not part of the simdutf library. They are part of a benchmark routine which relies on other libraries. We state: 

```
We include a few competitive solutions under the benchmarks/competition directory. They are provided for research purposes only.
```

The link you offer states that...

```
The code does not need to be replaced for license reasons. The files were
relicensed to a proper license by Unicode.org some 15 years ago, so we
fixed this issue for llvm by applying the "new" license terms to our copy.
```

We would, of course, invite the addition of utfcpp to our benchmarks. Pull request invited.
