### ISSUE TITLE
Split out `simdutf::validate_utf8()`

### ISSUE THREAD

**Issue by lpinca** [simdutf/simdutf#201]
Similar to https://github.com/simdjson/simdjson/issues/1348 from which `simdutf` was born.

It would be nice to have a C/C++ library for validating UTF-8 that provides _only_ the validation. `simdutf` could depend on this library, and external users could depend on only the validate library. `simdutf` is a bit too heavy to be used as a dependency for [`utf-8-validate`](https://www.npmjs.com/package/utf-8-validate), a Node.js module I maintain that only checks if a buffer contains valid UTF-8 encoded text.

Alternatively, it would be nice to have a way to reduce the binary size as much as possible, for example, by only exposing the wanted/needed functions.

Refs: https://github.com/simdjson/simdjson/issues/1348
Refs: https://github.com/websockets/utf-8-validate/pull/101
Refs: https://github.com/nodejs/node/pull/45803
Refs: https://github.com/nodejs/node/pull/45803#issuecomment-1363375858

**Comment by lemire** [comment]
Thanks for raising the issue.

**Comment by lemire** [comment]
Done

https://github.com/simdutf/is_utf8

If there is any further issue, please raise them at `is_utf8`.

**Comment by lpinca** [comment]
Thank you!
