### ISSUE TITLE
Add Windows on ARM support

### ISSUE THREAD

**Issue by StefanStojanovic** [simdutf/simdutf#216]
I've cloned this repo, built it, and tried running tests on a Windows 11 ARM64 machine. All tests failed with the `STATUS_INVALID_IMAGE_FORMAT (0xC000007B)` exit code. It would be good if Windows on ARM was supported in this project.

## Why and how I caught a lack of support for Windows on ARM

Recently, there's been an effort to replace icu with simdutf in Node.js. Another effort, which I'm a part of, is working on adding Windows on ARM to the list of officially supported platforms (adding it to CI, etc.). We've noticed that recently there was a huge increase in failing tests in Node.js daily test runs on ARM64. One of those runs can be viewed [here](https://gitlab.com/Linaro/windowsonarm/nightly/-/jobs/3757476282). After bisecting changes, I found out that this was caused by https://github.com/nodejs/node/pull/46471, and also https://github.com/nodejs/node/pull/46548 (I've seen a few more commits with similar changes, but they do not seem to break ARM64 tests).

**Comment by lemire** [comment]
I understand that you are using Visual Studio 2019 which does not run on ARM64. So you have to cross-compile:

```
cmake -G "Visual Studio 16 2019" -A ARM64  -DCMAKE_CROSSCOMPILING=1 -B buildarmold
cmake --build buildarmold
```

Take the produce binaries and copy them over to your ARM64 machine.

I have uploaded two binaries to my Google Drive, compiled with VS 2022 and VS 2019 respectively.

https://drive.google.com/drive/folders/123o3hC2Ws-_cY_AuPyUHH8CuxCxouZ_F

**Comment by lemire** [comment]
Note that if you try to run ARM64 binaries on x64, you will get an error (possibly `STATUS_INVALID_IMAGE_FORMAT`).

**Comment by lemire** [comment]
I am satisfied that this issue is fixed with PR https://github.com/simdutf/simdutf/pull/217  I will issue a patch release.

If there is still an issue, please document it carefully, in such a way that we can reproduce it.
