### ISSUE TITLE
Single-header version requires two files to be included

### ISSUE THREAD

**Issue by tocic** [simdutf/simdutf#222]
Why the single-header version of the library actually uses 2 files, one of which is `.cpp`? It's counterintuitive to see

```cpp
#include "simdutf.cpp"
#include "simdutf.h"
```

in the single-header version example.

Also, I expect to be able to install both versions at the same time. But now the amalgamated file from the zip archive and `include/simduft.h` have the same name, so it's unclear how to differentiate them in `CMAKE_INSTALL_INCLUDEDIR`.

**Comment by lemire** [comment]
From the README:

> You can create a single-header version of the library where all of the code is put into two files (simdutf.h and simdutf.cpp). We publish a zip archive containing these files, e.g., see https://github.com/simdutf/simdutf/releases/download/v3.2.2/singleheader.zip

There is a single header and a single source file.

We provide an example... here is a simplified version:

```C++
#include <iostream>
#include <memory>

#include "simdutf.cpp"
#include "simdutf.h"

int main(int , char *[]) {
  const char *source = "1234";
  // 4 == strlen(source)
  bool validutf8 = simdutf::validate_utf8(source, 4);
  if (validutf8) {
    std::cout << "valid UTF-8" << std::endl;
  } else {
    std::cerr << "invalid UTF-8" << std::endl;
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}
```

> Also, I expect to be able to install both versions at the same time. But now the amalgamated file from the zip archive and include/simduft.h have the same name, so it's unclear how to differentiate them in CMAKE_INSTALL_INCLUDEDIR.

I am not sure what you mean by both at the same time. You can either use the single-header version, in which case you just copy `simdutf.h` and `simdutf.cpp` to your project. Or else, if you want to use `simdutf` as an installed package of some sort, then you do so... Here is a CMake example...

```CMake
cmake_minimum_required(VERSION 3.15)

project(test_simdutf_install VERSION 0.1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
if(MSVC_VERSION GREATER 1910)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -permissive-")
endif()
find_package(simdutf REQUIRED)



file(WRITE main.cpp "
#include <iostream>
#include \"simdutf.h\"
int main(int argc, char *argv[]) {
   const char * ascii = \"1234\";
   bool validutf8 = simdutf::validate_utf8(ascii, 4);
   if(validutf8) {
       std::cout << \"valid UTF-8\" << std::endl;
   } else {
       std::cout << \"invalid UTF-8\" << std::endl;
       return EXIT_FAILURE;
   }
   char16_t utf16_output[4];
   // convert to UTF-16LE
   size_t utf16words = simdutf::convert_utf8_to_utf16le(ascii, 4, utf16_output);
   std::cout << \"wrote \" << utf16words << \" UTF-16 words.\" << std::endl;
   // It wrote utf16words * sizeof(char16_t) bytes.
   //
   // convert it back:
   char buffer[4];
   size_t utf8words = simdutf::convert_utf16le_to_utf8(utf16_output, utf16words, buffer);
   std::cout << \"wrote \" << utf8words << \" UTF-8 words.\" << std::endl;
   return EXIT_SUCCESS;
}")



add_executable(repro main.cpp)
target_link_libraries(repro PUBLIC simdutf::simdutf)
```

**Comment by lemire** [comment]
If you use the single-header release, then two files must be installed the header (there is just one) and the source file.

**Comment by lemire** [comment]
From CMake, you can use simdutf as a dependency as follows...

```CMake
cmake_minimum_required(VERSION 3.15)

project(simdutf_demo_install VERSION 0.1.0 LANGUAGES CXX)


set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
include(FetchContent)

FetchContent_Declare(
  simdutf
  GIT_REPOSITORY git@github.com:simdutf/simdutf.git
  GIT_SHALLOW TRUE
  GIT_TAG tags/v3.2.2
  )
FetchContent_MakeAvailable(simdutf)

file(WRITE main.cpp "
#include <iostream>
#include \"simdutf.h\"
int main(int argc, char *argv[]) {
   const char * ascii = \"1234\";
   bool validutf8 = simdutf::validate_utf8(ascii, 4);
   if(validutf8) {
       std::cout << \"valid UTF-8\" << std::endl;
   } else {
       std::cout << \"invalid UTF-8\" << std::endl;
       return EXIT_FAILURE;
   }
   char16_t utf16_output[4];
   // convert to UTF-16LE
   size_t utf16words = simdutf::convert_utf8_to_utf16le(ascii, 4, utf16_output);
   std::cout << \"wrote \" << utf16words << \" UTF-16 words.\" << std::endl;
   // It wrote utf16words * sizeof(char16_t) bytes.
   //
   // convert it back:
   char buffer[4];
   size_t utf8words = simdutf::convert_utf16le_to_utf8(utf16_output, utf16words, buffer);
   std::cout << \"wrote \" << utf8words << \" UTF-8 words.\" << std::endl;
   return EXIT_SUCCESS;
}")



add_executable(repro main.cpp)
target_link_libraries(repro PUBLIC simdutf::simdutf)
```

**Comment by lemire** [comment]
I am going to close the issue. The reporter is correct, they need two files for the single-header version.

**Comment by lemire** [comment]
As a last remark: we do not and probably never will support having both the single-header and another version of the simdutf library in the same project. It is the same code, same library, just packaged differently. Many users find the single-header version simpler.

**Comment by tocic** [comment]
> If you use the single-header release, then two files must be installed the header (there is just one) and the source file.

I understand, but I expected "single-header" to be "header-only". Otherwise, it's not clear what's the advantage of this version: it looks like you can just include the file https://github.com/simdutf/simdutf/blob/master/include/simdutf.h instead without any `.cpp`.

And I've never seen the inclusion of a `.cpp` file in other projects. You are free to use any distribution method you want, of course, just wanted to know your motivation for this.

> I am not sure what you mean by both at the same time

I meant simultaneous installation, not usage. So you can package both versions of the library and give users a chance to select the version they want. Currently, IIUC, you need to create 2 different packages or manually rename/move files.

**Comment by lemire** [comment]
If you believe that there is a shortcoming, please consider providing a pull request.
