### ISSUE TITLE
Excessive check for CLMUL on "Westmere" path

### ISSUE THREAD

**Issue by easyaspi314** [simdutf/simdutf#235]
The "Westmere" path's CPUID check explicitly checks for CLMUL, which doesn't appear to be used anymore (it is merely referenced in a comment). This excludes the original Nehalem processors which have POPCNT and SSE4.2, but not CLMUL.

**Comment by lemire** [comment]
You are correct. I invite a pull request.

**Comment by easyaspi314** [comment]
Should I change the references to Nehalem or just leave the technical misnomer as an implementation detail?

**Comment by easyaspi314** [comment]
Actually. I found another bug with the CPUID check, it doesn't check if the OS enabled AVX support, so this would crash if an AVX2-compatible CPU were running an OS that didn't support AVX2. Might as well fix both.

**Comment by lemire** [comment]
Fixed as per https://github.com/simdutf/simdutf/pull/236 by @easyaspi314 

Will be part of the next release.

**Comment by easyaspi314** [comment]
It seems that the commit was immediately reverted but the PR was locked.

**Comment by lemire** [comment]
Indeed. I was told that the merged PR was causing problems to one corporate user whereas things worked fine for them before.

**Comment by easyaspi314** [comment]
Do you want me to add the part without the macOS check? That will cause macOS to be locked to AVX2 though.

**Comment by lemire** [comment]
We will go with the current approach which is well tested and works for our users. If problems arise in real-world scenarios, we will take measures at that time.
