### ISSUE TITLE
crash when converting during the initialization of a static object.

### ISSUE THREAD

**Issue by JeffMcClintock** [simdutf/simdutf#252]
I have an object which is initialized something like:

```
namespace
{
int r = PerformSomeStuffAtStartup();
}
```

That object converts some strings. However the conversion crashes.

The crash is caused by `available_implementation_list::detect_best_supported()` returning

`&unsupported_singleton; // this should never happen?
`
 because `internal::available_implementation_pointers` is not initialized yet.

**Comment by JeffMcClintock** [comment]
// Static array of known implementations. We're hoping these get baked into the executable
// without requiring a static initializer.

nope.

**Comment by lemire** [comment]
See https://github.com/simdutf/simdutf/pull/253

**Comment by JeffMcClintock** [comment]
Thanks for the quick fix. I tried it here and it seems to work well in my scenario!
