### ISSUE TITLE
Dual license clarification

### ISSUE THREAD

**Issue by KTSnowy** [simdutf/simdutf#256]
Does the dual license mean that some files contain MIT code and others contain Apache-2.0 code (both licenses at the same time) or that the whole codebase is licensed as either MIT or Apache-2.0 (Choice of one or the other)?

**Comment by lemire** [comment]
The statement is 

> This code is made available under the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0.html) as well as the MIT license.

You get to pick.
