### ISSUE TITLE
Single-header version has no latin1

### ISSUE THREAD

**Issue by aspic-fish** [simdutf/simdutf#274]
Neither `simdutf.cpp` nor `simdutf.h` contains any `convert_latin1_to_...` or `convert_..._to_latin1` functions.

**Comment by lemire** [comment]
It is deliberate. The latin1 functionality is not yet released. It is still in development but should be released 'soon'.

@Nick-Nuon is on it and there is much demand for this functionality.

*However*, we do not want to release it before we feel it is ready for production use.
