### ISSUE TITLE
Add support of UTF-16BE

### ISSUE THREAD

**Issue by lemire** [simdutf/simdutf#3]
UTF-16 comes in two flavours (BE, LE). Some of the time, it can be distinguished with a BOM but often we must rely on the platforms' default. There are effectively no big endian platform left (other than legacy systems). I believe that UTF-16LE is effectively the default (e.g., under Windows). 

In time, we may want to support UTF-16BE. It involves a simple byte reversal.

**Comment by lemire** [comment]
@NicolasJiaxin I think you could address this issue. We just need to flip the order of the bytes so a single shuffle on the input register will do the job.

**Comment by clausecker** [comment]
On AVX-512, a rotate by 16 might be better as it runs on port 0 instead of the typically already overloaded port 5.

**Comment by lemire** [comment]
> On AVX-512, a rotate by 16 might be better as it runs on port 0 instead of the typically already overloaded port 5.

For rotating 16-bit words?

**Comment by clausecker** [comment]
Yes, a byte swap of word is just a rotation by 8 places.  No need to use a `vpshufb` or other permutation op unless there's lots of space in port 5.  It might even be possible to do the decoding without swapping the bytes in many situations.

**Comment by lemire** [comment]
I think we first want to build up fallback, NEON, SSE... And all of the SIMD approach will support it with a cheap shuffle. And then AVX-512 might require a different strategy.

**Comment by clausecker** [comment]
SSE/SSE2 doesn't have `pshufb`.  NEON can do them but I think there's a better way (maybe something like `SRI`).  There is unfortunately not a single solution that solves all the problems.

**Comment by lemire** [comment]
Our SSE-based kernel requires pshufb.

**Comment by clausecker** [comment]
Ah, okay.  So it's SSSE3 or better.  Makes sense.

**Comment by lemire** [comment]
Requirements of the kernel at https://github.com/simdutf/simdutf/blob/c72d881c4005deafb012f5ac7491bf7a9b219130/src/simdutf/westmere/implementation.h#L16

**Comment by NicolasJiaxin** [comment]
@lemire What is the C++ way of doing this? With templates to distinguish between LE and BE?

**Comment by clausecker** [comment]
One solution would be to have a load function (or set of them) in the template.  The LE version just does the load, the BE version does a load followed by a byte swap (or rotate by 8 on each word).  Code would be more complex to understand though.

**Comment by clausecker** [comment]
That does not look like it'll vectorise well.  It does not need to be generalised either.  Solve the problem at hand, not a hypothetical, more general problem.

**Comment by NicolasJiaxin** [comment]
And from a front-end point of view, it is better if we have separate functions like `validate_utf16le and `validate_utf16be` and pass the appropriate template parameter rather than one general function like `validate_utf16` and having the user pass in the template parameter?

**Comment by clausecker** [comment]
I would say so.  Makes the interface easier to use.

**Comment by lemire** [comment]
It is surely subjective but I agree with Robert. Others would prefer a templated front-end.

**Comment by clausecker** [comment]
Given that there are unfortunately no word rotates in AVX-512, this might be as good as it gets indeed.  Only better option could be to redo the whole algorithm in the wrong byte order, which might not be as complex as it sound.

**Comment by NicolasJiaxin** [comment]
Should I also duplicate every test that we have for UTF-16LE or just a few?

**Comment by NicolasJiaxin** [comment]
@lemire When you have time, could you extend https://github.com/lemire/unicode_lipsum to include UTF-16BE files so that I do some benchmarking?
