### ISSUE TITLE
validate_utf8_with_errors is insufficienty documented

### ISSUE THREAD

**Issue by amluto** [simdutf/simdutf#304]
I need a C++ function to replace invalid utf8 data with replacement characters, a la #147 or Python's `.decode(errors='replace')`.  The `validate_utf8_with_errors` function is the obvious starting point, but the documentation is poor, so I gave up.  (Seriously, I just want this function, the output needs to be unconditionally valid utf8, and I don't want to base it on something ambiguous.)

Here's how far I've gotten:

```c++
std::string utf8_replace_invalid(std::string s)
{
    std::string out;
    simdutf::result r = simdutf::validate_utf8_with_errors(s.data(), s.length());
    if (r.error == simdutf::SUCCESS) {
        // Fast path: move the input
        out = std::move(s);
        return s;
    }

    // Sadly, simdutf doesn't actually know how to replace invalid characters.
    // So we're stuck rolling our own.
    size_t inpos = 0, outpos = 0;
    out.reserve(s.length() + 2);

    // Okay, the docs are not so great.  They say:
    //  On error, the error field indicates the type of error encountered and
    //  the position field indicates its word position in the input string.
    // First, there is no "position" field.  There's a "count" field.  Second,
    // is the position equal to the number of valid bytes (a utf8 "word" is
    // presumably a byte, but the standard term is "code unit", not "word"),
    // or is it the position of the error, which could be in the middle or
    // at the end of a malformed group of code units which fail to form a valid
    // code point?
}
```

And you can see where I got stuck.  The returned structure from `validate_utf8_with_errors` is underspecified.

With adequate documentation, I might actually finish this project.  It would be even nicer if the documentation were improved and #147 were implemented :)

**Comment by lemire** [comment]
The documentation, from the README, is...

```C++
struct result {
  error_code error; // see `struct error_code`.
  size_t count; // In case of error, indicates the position of the error in the input.
  // In case of success, indicates the number of words validated/written.
};
```

If we claim that there is a position field, then I will correct this in our documentation as an upcoming PR.

It seems reasonably well defined, but it is not meant to allow you to do transcoding with replacement... which is something that we plan to provide in the future.

**Comment by amluto** [comment]
The docs claim there is a position field: they say [`On error, the `error` field indicates the type of error encountered and the `position` field indicates its word position in the input string.`](https://github.com/simdutf/simdutf/blob/ee904f6ca6ce976050754ebecfa950a638f76df7/README.md?plain=1#L314).

**Comment by lemire** [comment]
@amluto Agreed. Good catch. Let us fix these issues.

Currently, we do not support transcoding with replacement, but pull requests are invited.

**Comment by lemire** [comment]
Fixed by PR https://github.com/simdutf/simdutf/pull/306 

Thanks for your feedback.

We do invite pull requests for issue https://github.com/simdutf/simdutf/issues/147 We currently lack the functionality to implement it efficiently so it remains future work.
