### ISSUE TITLE
count_code_points

### ISSUE THREAD

**Issue by alantudyk** [simdutf/simdutf#321]
https://github.com/simdutf/simdutf/blob/ed994fc32d27a2d70671b838403739c5be087fbe/src/generic/utf8.h#L15-L16
Why not just:
```C
uint64_t utf8_continuation_mask = input.gt(-65);
count += count_ones(utf8_continuation_mask);
```
?

**Comment by lemire** [comment]
Want to issue a pull request? I’m curious as to whether it would have a visible performance difference.

**Comment by alantudyk** [comment]
> pull request?

No.

**Comment by lemire** [comment]
@Nick-Nuon Want to have a look?

**Comment by lemire** [comment]
@alantudyk So as I expected, it does not affect the performance. We will still follow on your proposal because it slightly simplifies the code which is good from a software engineering point of view (better readability).

Thanks @Nick-Nuon

**Comment by alantudyk** [comment]
https://github.com/simdutf/simdutf/blob/52ec2b3cd5dbeae8928600d213dee299b62b5979/src/generic/utf8.h#L14-L16

Missing space (L15).

You should add any formatter / style checker to CI.
