### ISSUE TITLE
Building as a shared library but static is hardcoded

### ISSUE THREAD

**Issue by SimeonStoykovQC** [simdutf/simdutf#331]
I would like to create a [conda recipe](https://github.com/conda-forge/staged-recipes/pull/24320) for this package. For this, I would like to build the source as a shared library. However, the static option is currently hardcoded:

https://github.com/simdutf/simdutf/blob/9317e67a3ebfb2914bd17e6c5fef4bb8f5f0f1d9/src/CMakeLists.txt#L6

Is there any specific reason for this?
Thanks!

**Comment by lemire** [comment]
The upcoming release with directly build dynamic libraries on demand.

The reason we did not until now has to do with the fact that Windows make it difficult to find newly built DLLs. Unless they are in the same directory or in a directly that is part of the PATH variable, you have to copy them physically. It is annoying.

**Comment by lemire** [comment]
I am expecting to release later today.
