### ISSUE TITLE
#define conflict (`ERROR_H`)

### ISSUE THREAD

**Issue by p0358** [simdutf/simdutf#350]
After including simdbuf into my precompiled header, I found out that my project doesn't compile anymore. The culprit is:
https://github.com/simdutf/simdutf/blob/db8bf050e5c2a9ce83833cf013ca043a2a40d927/include/simdutf/error.h#L1-L2

I already have another file in the project that's called `Error.h` and also defines `ERROR_H`.

I see that includes of other files are prefixed with `SIMDUTF_`, meaning that this is an accidental ommission and that the define of `ERROR_H` should be changed to something akin to `SIMDUTF_ERROR_H`...

**Comment by lemire** [comment]
>  this is an accidental ommission

That's correct.
