### ISSUE TITLE
Package for Debian/Ubuntu? 

### ISSUE THREAD

**Issue by jaceksan** [simdutf/simdutf#374]
There are packages in Fedora repos, but DEB packages do not exist.

The alternative option is to document how to build and install everything from the source.
I am not an experienced user, I just need to build another tool (Turbodbc) and am blocked by missing `simdutf` library.

**Comment by jaceksan** [comment]
I downloaded Fedora packages, extracted include/lib64, and copied it to /usr/include resp. /usr/lib.
Now I am able to install the latest Turbodbc (4.11).
But it's cumbersome...

**Comment by lemire** [comment]
You have opened an issue at the wrong location. We just maintain the library, we do not distribute the packages. Your Linux distribution does. 

Fedora and FreeBSD have a simdutf package. If you find it inconvenient that Debian does not, and I can see why that would be the case, you need to raise the issue with Debian... or [offer to provide the package yourself](https://www.debian.org/doc/manuals/developers-reference/pkgs.html). My understanding is that it is not too difficult to find someone to build and submit the package, but I personally do not know anyone who works on Debian.


The tool you are using (turbodbc) could also bundle simdutf directly.

I am closing this issue. Please raise your issue with Debian.

**Comment by jaceksan** [comment]
I understand and agree.
Before I or anyone else get simdutf to Debian repos - could you, please, describe how to install simdutf from source to Debian?
I would appreciate it ;-)
