### ISSUE TITLE
Incorrect processor detection when cross compiling

### ISSUE THREAD

**Issue by ReimuNotMoe** [simdutf/simdutf#379]
I'm cross compiling simdutf for a MIPS processor and the option `-mno-avx256-split-unaligned-load` still got added to CFLAGS.

The problem seems to be caused by https://github.com/simdutf/simdutf/blob/master/src/CMakeLists.txt#L26-L28. Commenting out these lines have fixed this problem.

Here are the output from CMake:
```
-- Python found, we are going to amalgamate.py.
-- The tests are enabled.
-- Iconv was found!
-- Iconv is part of the C library.
-- looking for static C++ library in /data3/buildroot-2023.02.3/output/host/lib/gcc/mipsel-buildroot-linux-gnu/11.4.0
-- libstdc++.a found
-- The benchmarks can be enabled by setting SIMDUTF_BENCHMARKS, e.g., -D SIMDUTF_BENCHMARKS=ON.
-- Compiling using the C++ standard:11

-- Configuring done
-- Generating done
-- Build files have been written to: ......

Problems were encountered while collecting compiler information:
	mipsel-buildroot-linux-gnu-g++.br_real: error: unrecognized command-line option '-mno-avx256-split-unaligned-load'
	mipsel-buildroot-linux-gnu-g++.br_real: error: unrecognized command-line option '-mno-avx256-split-unaligned-store'
```

**Comment by lemire** [comment]
The CMake documentation states that...

> When cross-compiling, a [CMAKE_TOOLCHAIN_FILE](https://cmake.org/cmake/help/latest/variable/CMAKE_TOOLCHAIN_FILE.html#variable:CMAKE_TOOLCHAIN_FILE) should set the CMAKE_SYSTEM_PROCESSOR variable to match target architecture that it specifies

Can you confirm that you are following the CMake requirements as stated in the documentation?

If so, can you give us the value of CMAKE_SYSTEM_PROCESSOR in your case?

**Comment by ReimuNotMoe** [comment]
I'm using the Jetbrains CLion IDE and I configured the toolchain in the GUI.

![image](https://github.com/simdutf/simdutf/assets/34613827/519d251c-2167-4cc2-8bfc-1b1f901c56ca)

So I guess I should report this issue to Jetbrains then.
