### ISSUE TITLE
SIMDUTF_CAN_ALWAYS_RUN_* macros broken

### ISSUE THREAD

**Issue by jakubjelinek** [simdutf/simdutf#391]
As mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=2273542#c14 the SIMDUTF_CAN_ALWAYS_RUN_{HASWELL,ICELAKE,WESTMERE} macros are broken at least for GCC.
This is because GCC (since ~4.7 when not using -save-temps, since 14 when preprocessing separately from compilation) on #pragma GCC target ISA changes undefines/defines the predefined preprocessor macros like `__AVX2__`, so that they reflect the current set of the enabled/disabled ISAs in the region.
When you
```c
#define SIMDUTF_CAN_ALWAYS_RUN_AVX2 __AVX2__
#if SIMDUTF_CAN_ALWAYS_RUN_AVX2
#else
#pragma GCC push_options
#pragma GCC target ("avx2")
#endif
...
#if SIMDUTF_CAN_ALWAYS_RUN_AVX2
#else
#pragma GCC pop_options
#endif
```
and compile this with -mno-avx2, the first `SIMDUTF_CAN_ALWAYS_RUN_AVX2` use will evaluate to 0 because `__AVX2__` is not defined, but then `#pragma GCC target ("avx2")` defines it, on the second use it will evaluate to 1 because `__AVX2__` is defined to 1 there and finally `#pragma GCC pop_options` will undefine it again.
The code clearly expects it to evaluate the same in both cases, otherwise there is a misbalance, which in the rhbz case causes unsupported_implementation to be compiled with avx2,bmi,lzcnt,popcnt isas.

I'd suggest either change macros like:
```c
#define SIMDUTF_CAN_ALWAYS_RUN_HASWELL ((SIMDUTF_IMPLEMENTATION_HASWELL) && (SIMDUTF_IS_X86_64) && (__AVX2__))
```
to
```c
#if ((SIMDUTF_IMPLEMENTATION_HASWELL) && (SIMDUTF_IS_X86_64) && (__AVX2__))
#define SIMDUTF_CAN_ALWAYS_RUN_HASWELL 1
#else
#define SIMDUTF_CAN_ALWAYS_RUN_HASWELL 0
#endif
```
Then it will have a constant value through the whole compilation unit.

**Comment by jakubjelinek** [comment]
What GCC normally uses in its intrinsic headers is:
```c
#ifndef __AVX2__
#pragma GCC push_options
#pragma GCC target("avx2")
#define __DISABLE_AVX2__
#endif /* __AVX2__ */
```
at the start and
```c
#ifdef __DISABLE_AVX2__
#undef __DISABLE_AVX2__
#pragma GCC pop_options
#endif /* __DISABLE_AVX2__ */
```
at the end.

**Comment by lemire** [comment]
Solved with last release. Thanks.
