### ISSUE TITLE
Possible Issue With .pc.in?

### ISSUE THREAD

**Issue by spinicist** [simdutf/simdutf#411]
Hello,

I'd like to raise awareness of this issue on the vcpkg repo: https://github.com/microsoft/vcpkg/issues/38028

As best I can tell, the problem is:

1. The simdutf.pc.in file has a leading space at the front of each line
2. Older versions of pkgconf (but not pkg-config) barf on this leading space

I barely understand pkg-config so I don't know if leading whitespace is officially a syntax error or not. Would you be amenable to simple PR removing the leading spaces?

**Comment by WojciechMula** [comment]
Please submit PR, I think it won't be a problem.

**Comment by spinicist** [comment]
I have created #412

**Comment by dg0yt** [comment]
Upstream merged the pc file fix, and they create releases frequently. Can we wait?

**Comment by spinicist** [comment]
@dg0yt Did you mean to post that on the vcpkg thread rather than here?

@WojciechMula @lemire Do you have a planned date for the next release? It looks like you're releasing every couple of weeks at the moment, I am very impressed by that schedule! Also thanks for being so responsive.

**Comment by dg0yt** [comment]
> Did you mean to post that on the vcpkg thread rather than here?

:man_facepalming:  yes

**Comment by lemire** [comment]
@spinicist There is what appears to be a bug in our RISC V support. I think @WojciechMula will handle the fix soon. Right after we will need to do a patch release.

Could be next week or soon after.

If there is a rush, we can issue a release sooner.

**Comment by spinicist** [comment]
I came here to post that this week is fine, but was greeted with version 5.2.5 released 17 minutes ago!

Thank you so much. This is a level above how fast most projects move. 🥳
