### ISSUE TITLE
UTF-32 endian support

### ISSUE THREAD

**Issue by jtsylve** [simdutf/simdutf#418]
There doesn't seem to be equivalent LE and BE support for UTF-32 as UTF-16.  For example there is no `simdutf::validate_utf32le_with_errors` or `simdutf::validate_utf32be_with_errors` Is there is an intention to add both LE and BE support for UTF-32?  

Also do the current UTF-32 options assume little endian or are they big endian on BE platforms?

**Comment by lemire** [comment]
UTF-32 uses native ordering when not specified. So it is BE on BE platforms and LE on LE platforms.

Note that UTF-32 is not an exchange format (data online is either in UTF-8 or UTF-16). UTF-32, when use, is an internal format.

**Comment by lemire** [comment]
Note that it is already documented :

<img width="882" alt="Screenshot 2024-04-30 at 2 59 37 PM" src="https://github.com/simdutf/simdutf/assets/391987/27babc82-03df-4327-bf50-5245de1f0eb0">
