### ISSUE TITLE
out of bounds write in convert_utf8_to_utf32_with_errors

### ISSUE THREAD

**Issue by pauldreik** [simdutf/simdutf#478]
The following produces an out of bounds write on icelake, in the file src/scalar/utf8_to_utf32/utf8_to_utf32.h:105

```cpp
TEST(issue_478)
{
    const unsigned char data[] = {0x20, 0xdf, 0xbb, 0xcd, 0x8d, 0xcf, 0xbb, 0x20, 0x20, 0xdf, 0xbb,
                                  0xdf, 0xbb, 0xcd, 0xbb, 0xcd, 0xbb, 0xde, 0xbb, 0xdf, 0xbb, 0xcd,
                                  0xa9, 0xdf, 0xbb, 0xdf, 0xbb, 0xdf, 0xbb, 0xdf, 0xbb, 0xcd, 0xbb,
                                  0xcd, 0xbb, 0xde, 0xbb, 0xdf, 0xbb, 0xcd, 0xa9, 0xd8, 0xbb, 0xdf,
                                  0xbb, 0xdf, 0xbb, 0xdf, 0xbb, 0xdf, 0xbb, 0xdf, 0xb3, 0xdf, 0xbb,
                                  0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0xb9};
    constexpr std::size_t data_len_bytes = sizeof(data);
    constexpr std::size_t data_len = data_len_bytes / sizeof(char);
    const auto validation1 = implementation.validate_utf8_with_errors((const char *) data, data_len);
    ASSERT_EQUAL(validation1.count, 64);
    ASSERT_EQUAL(validation1.error, simdutf::error_code::TOO_LONG);

    const auto outlen = implementation.utf32_length_from_utf8((const char *) data, data_len);
    ASSERT_EQUAL(outlen, 38);
    std::vector<char32_t> output(outlen);
    const auto r = implementation.convert_utf8_to_utf32_with_errors((const char *) data,
                                                                    data_len,
                                                                    output.data());
    ASSERT_EQUAL(r.error, simdutf::error_code::SUCCESS);
    ASSERT_EQUAL(r.count, 1234);
    const std::vector<char32_t> expected_out{};
    ASSERT_TRUE(output.size() == expected_out.size());
    for (std::size_t i = 0; i < output.size(); ++i) {
        ASSERT_EQUAL(+output.at(i), +expected_out.at(i));
    };
}
```

The output:

> ==10140==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x50e0000000d8 at pc 0x5637739e8ab9 bp 0x7ffc8ee8c370 sp 0x7ffc8ee8c368
> WRITE of size 4 at 0x50e0000000d8 thread T0
>     #0 0x5637739e8ab8 in simdutf::scalar::(anonymous namespace)::utf8_to_utf32::convert_with_errors(char const*, unsigned long, char32_t*) /home/pauldreik/code/delaktig/simdutf/src/scalar/utf8_to_utf32/utf8_to_utf32.h:105:23
>     #1 0x563773a7f31f in simdutf::scalar::(anonymous namespace)::utf8_to_utf32::rewind_and_convert_with_errors(unsigned long, char const*, unsigned long, char32_t*) /home/pauldreik/code/delaktig/simdutf/src/scalar/utf8_to_utf32/utf8_to_utf32.h:197:16
>     #2 0x563773a721ae in simdutf::icelake::implementation::convert_utf8_to_utf32_with_errors(char const*, unsigned long, char32_t*) const /home/pauldreik/code/delaktig/simdutf/src/icelake/implementation.cpp:682:18
>     #3 0x563773981dd2 in test_impl_issue_convert_utf8_to_utf32_with_errors_48671aed05deb2eb(simdutf::implementation const&) /home/pauldreik/code/delaktig/simdutf/tests/fuzzercrashes.cpp:424:35
>     #4 0x56377397f0cf in issue_convert_utf8_to_utf32_with_errors_48671aed05deb2eb(simdutf::implementation const&) /home/pauldreik/code/delaktig/simdutf/tests/fuzzercrashes.cpp:407:1

**Comment by lemire** [comment]
Fixed in https://github.com/simdutf/simdutf/pull/481
