### ISSUE TITLE
out of bounds write in convert_utf8_to_utf16be_with_errors on icelake

### ISSUE THREAD

**Issue by pauldreik** [simdutf/simdutf#479]
The following code:
```cpp
TEST(issue_479)
{
    const unsigned char data[] = {0xf1, 0xa1, 0xa9, 0xa9, 0xf1, 0xa1, 0xa9, 0xa9, 0xf1, 0xa1, 0xa9,
                                  0xb2, 0xf1, 0xb9, 0xa1, 0xa9, 0xf1, 0xa1, 0xa9, 0xa9, 0xf1, 0xa1,
                                  0xa9, 0xa9, 0xf1, 0xa9, 0xa1, 0xa9, 0xf1, 0xa1, 0xae, 0xa6, 0xf1,
                                  0xa1, 0xa9, 0xa9, 0xf1, 0xa9, 0xa1, 0xa9, 0xf1, 0xa1, 0xa9, 0xa9,
                                  0xf1, 0xa1, 0xa9, 0xa9, 0xf1, 0xa1, 0xa9, 0xa9, 0xf1, 0xa1, 0xa9,
                                  0xa9, 0xf1, 0xa1, 0xa9, 0xa9, 0xf1, 0xa0, 0xa0, 0xa0, 0xa0};
    constexpr std::size_t data_len_bytes = sizeof(data);
    constexpr std::size_t data_len = data_len_bytes / sizeof(char);
    const auto validation1 = implementation.validate_utf8_with_errors((const char *) data, data_len);
    ASSERT_EQUAL(validation1.count, 64);
    ASSERT_EQUAL(validation1.error, simdutf::error_code::TOO_LONG);

    const auto outlen = implementation.utf16_length_from_utf8((const char *) data, data_len);
    ASSERT_EQUAL(outlen, 32);
    std::vector<char16_t> output(outlen);
    const auto r = implementation.convert_utf8_to_utf16be_with_errors((const char *) data,
                                                                      data_len,
                                                                      output.data());
    ASSERT_EQUAL(r.error, simdutf::error_code::SUCCESS);
    ASSERT_EQUAL(r.count, 1234);
    const std::vector<char16_t> expected_out{};
    ASSERT_TRUE(output.size() == expected_out.size());
    for (std::size_t i = 0; i < output.size(); ++i) {
        ASSERT_EQUAL(+output.at(i), +expected_out.at(i));
    };
}

```

gets the following error:
_==13466==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x5060000013e0 at pc 0x55f14bdb51e6 bp 0x7ffda01f8790 sp 0x7ffda01f8788
WRITE of size 2 at 0x5060000013e0 thread T0
    #0 0x55f14bdb51e5 in simdutf::result simdutf::scalar::(anonymous namespace)::utf8_to_utf16::convert_with_errors<(simdutf::endianness)1>(char const*, unsigned long, char16_t*) /home/pauldreik/code/delaktig/simdutf/src/scalar/utf8_to_utf16/utf8_to_utf16.h:177:23
    #1 0x55f14c0c3af0 in simdutf::result simdutf::scalar::(anonymous namespace)::utf8_to_utf16::rewind_and_convert_with_errors<(simdutf::endianness)1>(unsigned long, char const*, unsigned long, char16_t*) /home/pauldreik/code/delaktig/simdutf/src/scalar/utf8_to_utf16/utf8_to_utf16.h:234:16
    #2 0x55f14be2b3ce in simdutf::result simdutf::icelake::(anonymous namespace)::fast_avx512_convert_utf8_to_utf16_with_errors<(simdutf::endianness)1>(char const*, unsigned long, char16_t*) /home/pauldreik/code/delaktig/simdutf/src/icelake/icelake_from_utf8.inl.cpp:43:27
    #3 0x55f14be2ae7c in simdutf::icelake::implementation::convert_utf8_to_utf16be_with_errors(char const*, unsigned long, char16_t*) const /home/pauldreik/code/delaktig/simdutf/src/icelake/implementation.cpp:575:11
    #4 0x55f14bd56822 in test_impl_issue_convert_utf8_to_utf16be_with_errors_b3948b7243524254(simdutf::implementation const&) /home/pauldreik/code/delaktig/simdutf/tests/fuzzercrashes.cpp:455:35_

**Comment by lemire** [comment]
Fixed in https://github.com/simdutf/simdutf/pull/481
