### ISSUE TITLE
out of bounds write in utf16_length_from_utf8 (icelake)

### ISSUE THREAD

**Issue by pauldreik** [simdutf/simdutf#483]
This testcase causes an out of bounds write in convert_utf8_to_utf16be_with_errors:

```cpp
TEST(issue_483)
{
    const unsigned char data[] = {0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
                                  0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
                                  0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
                                  0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
                                  0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
                                  0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0xa9};
    constexpr std::size_t data_len_bytes = sizeof(data);
    constexpr std::size_t data_len = data_len_bytes / sizeof(char);
    const auto validation1 = implementation.validate_utf8_with_errors((const char *) data, data_len);
    ASSERT_EQUAL(validation1.count, 64);
    ASSERT_EQUAL(validation1.error, simdutf::error_code::TOO_LONG);

    const auto outlen = implementation.utf16_length_from_utf8((const char *) data, data_len);
    ASSERT_EQUAL(outlen, 64);
    std::vector<char16_t> output(outlen);
    const auto r = implementation.convert_utf8_to_utf16be_with_errors((const char *) data,
                                                                      data_len,
                                                                      output.data());
    ASSERT_EQUAL(r.error, simdutf::error_code::TOO_LONG);
    ASSERT_EQUAL(r.count, 64);
}
```

The error output is:

> ==11273==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x50c000000180 at pc 0x555555805b55 bp 0x7fffffffcbb0 sp 0x7fffffffcba8
> WRITE of size 2 at 0x50c000000180 thread T0
>     #0 0x555555805b54 in simdutf::result simdutf::scalar::(anonymous namespace)::utf8_to_utf16::convert_with_errors<(simdutf::endianness)1>(char const*, unsigned long, char16_t*) /home/pauldreik/code/delaktig/simdutf/src/scalar/utf8_to_utf16/utf8_to_utf16.h:124:23
>     #1 0x555555b4f5b2 in simdutf::result simdutf::scalar::(anonymous namespace)::utf8_to_utf16::rewind_and_convert_with_errors<(simdutf::endianness)1>(unsigned long, char const*, unsigned long, char16_t*) /home/pauldreik/code/delaktig/simdutf/src/scalar/utf8_to_utf16/utf8_to_utf16.h:234:16
>     #2 0x5555558870a0 in simdutf::result simdutf::icelake::(anonymous namespace)::fast_avx512_convert_utf8_to_utf16_with_errors<(simdutf::endianness)1>(char const*, unsigned long, char16_t*) /home/pauldreik/code/delaktig/simdutf/src/icelake/icelake_from_utf8.inl.cpp:53:27
>     #3 0x5555558861d4 in simdutf::icelake::implementation::convert_utf8_to_utf16be_with_errors(char const*, unsigned long, char16_t*) const /home/pauldreik/code/delaktig/simdutf/src/icelake/implementation.cpp:577:11
>     #4 0x5555557a44b6 in test_impl_issue_convert_utf8_to_utf16be_with_errors_e2fd989f3a9c7a59(simdutf::implementation const&) /home/pauldreik/code/delaktig/simdutf/tests/fuzzercrashes.cpp:557:35
>     #5 0x5555557a187f in issue_convert_utf8_to_utf16be_with_errors_e2fd989f3a9c7a59(simdutf::implementation const&) /home/pauldreik/code/delaktig/simdutf/tests/fuzzercrashes.cpp:540:1
> 

The other implementations (than icelake) don't have this problem. I am not sure how to think about this. On one hand, the outputbuffer was resized to the size that utf16_length_from_utf8 gave. On the other hand, trying to convert invalid data should maybe not surprise anyone that it fails. It is however meaningful that a user wants to convert the data up to the first fault. So I lean towards thinking this is a bug.

**Comment by lemire** [comment]
On it.
