### ISSUE TITLE
implementation difference on base64_to_binary on utf16 on input 15626 (0x3D0A)  (fallback)

### ISSUE THREAD

**Issue by pauldreik** [simdutf/simdutf#503]
The following test containing the input [㴊](https://en.wiktionary.org/wiki/%E3%B4%8A):

```cpp
TEST(issue_503)
{
    std::array<char16_t, 1> data{15626}; // 0x3D0A
    std::vector<char> out(1);
    const auto r = implementation.base64_to_binary(data.data(),
                                                   data.size(),
                                                   out.data(),
                                                   simdutf::base64_default);
    // fallback gives INVALID_BASE64_CHARACTER
    ASSERT_EQUAL(r.error, simdutf::error_code::SUCCESS);
    ASSERT_EQUAL(r.count, 0);
}
```

gives different results for the fallback implementation and the other x86 implementations.
I don't know how to fix it.

UPDATE: I now see that this input violates  the precondition 

>  * @param input         the base64 string to process, in ASCII stored as 16-bit units

but I will not close it yet, maybe there is something to learn from this case.

**Comment by lemire** [comment]
On it.

**Comment by lemire** [comment]
> UPDATE: I now see that this input violates the precondition

This is an actual bug as far as I can tell.
