### ISSUE TITLE
benchmarks in release 5.3.7 fails to compile

### ISSUE THREAD

**Issue by diizzyy** [simdutf/simdutf#512]
https://github.com/simdutf/simdutf/blob/master/benchmarks/base64/benchmark_base64.cpp#L12 references libbase64.h which isn't in repo

**Comment by lemire** [comment]
It is an external dependency:

https://github.com/simdutf/simdutf/blob/master/benchmarks/base64/CMakeLists.txt

We build the benchmarks in CI prior to every release.

Can you provide the exact CMake command you have entered and the exact error mess?

**Comment by diizzyy** [comment]
Ahh I see, I didn't see any checks for it "offline"/locally but that explains it.

**Comment by lemire** [comment]
Closing
