### ISSUE TITLE
relax avx512 threshold for zen5

### ISSUE THREAD

**Issue by ronag** [simdutf/simdutf#521]
zen5 has quite a low avx512 overhead and hence it might make sense to lower the minimum input size for this architecture.

http://www.numberworld.org/blogs/2024_8_7_zen5_avx512_teardown/

**Comment by lemire** [comment]
@ronag Can you be specific regarding the code you are thinking about?

**Comment by lemire** [comment]
@ronag I don't think we have an avx512 threshold in simdutf?

We exclude older Intel CPUs (e.g., Skylake X) because AVX-512 did poorly generally on these processors. Starting with Ice Lake, Rocket Lake, Zen 4 and Zen 5... AVX-512 is generally a win so we are not shy about using it.

**Comment by ronag** [comment]
Example: https://github.com/simdutf/simdutf/blob/eddf7e235cd722d73cb9cba82e30e4442f2a6f4e/src/westmere/implementation.cpp#L702

**Comment by lemire** [comment]
@ronag You are pointing at the westmere code which will only ever run on very old x64 processors. None of the two paths use AVX-512.

The relevant code for Zen 5 is the icelake kernel:

https://github.com/simdutf/simdutf/blob/eddf7e235cd722d73cb9cba82e30e4442f2a6f4e/src/icelake/implementation.cpp#L1289

There is still a branch (with long strings and short strings). But notice that both paths use AVX-512. Yet the algorithm differs. In one path, we process blocks of 256 bytes on the assumption that there are potentially several of time (so here, we assume 8 blocks of 256 bytes).

This could be tuned further, meaning that I just set the 2048 arbitrarily. We could adjust it. But it has to be at least 256.

Importantly, we *always* use AVX-512... except when the string is under 64 characters. For string under 64 characters, we just use a scalar routine. It would be _easy_ to replace the scalar routine with a masked load...
