### ISSUE TITLE
fuzz implementations

### ISSUE THREAD

**Issue by ronag** [simdutf/simdutf#522]
I've noticed there has been some bugs reported where the different implementations differ. One possible way to test for such failures is to generate lots of random data and call all the different implementations and ensure they produce the same result.

This is more time efficient than create specific unit tests for each case.

**Comment by ronag** [comment]
@pauldreik

**Comment by pauldreik** [comment]
This is an excellent idea and is called "differential fuzzing".

That is exactly what I have been pursuing the last weeks and has uncovered quite a few issues. Not all is upstreamed yet, but you can see an example here: 

https://github.com/simdutf/simdutf/blob/eddf7e235cd722d73cb9cba82e30e4442f2a6f4e/fuzz/conversion.cpp#L371-L468
