### ISSUE TITLE
copy_utf8

### ISSUE THREAD

**Issue by ronag** [simdutf/simdutf#550]
Would be nice to have a `copy_utf8` function that combines the following into one operation:

```cpp
if (validate_utf8(src, size)) {
    memcpy(dst, src, size)
} 
```

Refs: https://github.com/nodejs/node/pull/54526

**Comment by lemire** [comment]
@ronag How would you call it?

**Comment by anonrig** [comment]
copy_if_valid()?

**Comment by lemire** [comment]
@anonrig @ronag Someone wants to code it up?

It might be three lines of code... could be right here....

https://github.com/simdutf/simdutf/blob/14d1b14dd33fbabc2fb212c91c3d3adaa2b3e3e0/include/simdutf/implementation.h#L42

**Comment by ronag** [comment]
actually what we need is a `latin1_to_utf8` with an output limit

**Comment by lemire** [comment]
> actually what we need is a latin1_to_utf8 with an output limit

It might be easier to code a function which tells you how many latin1 characters to read.

**Comment by ronag** [comment]
> It might be easier to code a function which tells you how many latin1 characters to read.

That would require scanning the string twice which is inefficient.
