### ISSUE TITLE
[Base64] What about the RFC 2045

### ISSUE THREAD

**Issue by zhanglistar** [simdutf/simdutf#561]
Hi, guys great work on fast base64. May I ask a question that how could I use this library to support RFC 2045? Thanks in advance.

**Comment by lemire** [comment]
We support base64 encoding and decoding which is a small part of RFC 2045. We have no plan to support email formats. It seems to be quite outside the scope of simdutf. However, it would be possible to use simdutf in an RFC 2045 implementation, but it would have to be different project/library.
