### ISSUE TITLE
discuss: introduce clang format

### ISSUE THREAD

**Issue by pauldreik** [simdutf/simdutf#562]
The code is sometimes inconsistently formatted. That does not bother me.

However, when developing, it is very convenient if one can use auto formatting. I also think it leads to cleaner pull requests since unrelated white space changes are less likely to occur. It is also easier for contributors to adhere to the code style without effort (most IDE-s support formatting).

This comes up now when [working with the span interface ](https://github.com/simdutf/simdutf/issues/557)- it would be nice to have some kind of machine enforceable formatting in place before I start.

The established practice is to have a .clang-format checked in at the root level. There is already one for the [fuzzer subdirectory](https://github.com/simdutf/simdutf/blob/master/fuzz/.clang-format).

The downsides: 
 - the project has to agree on a style. I mostly don't mind which one.
 - (proposed, but debatable): making one big reformat commit, which might inconvenience people doing git blame. [there seems to be a handy way to ignore it](https://akrabat.com/ignoring-revisions-with-git-blame/)
 - care has to be taken for [header reordering](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#sortincludes) - this should be disabled in the .clang-format file. otherwise amalgamation and more may break (this project is somewhat special in this regard). This is turned off in the fuzzer subdirectory.
 - sometimes clang format can give inconsistencies. a recent example is handling concepts, which changed in recent versions. considering the codebase is mostly C++11, I don't think this is a problem.

I suggest to introduce a CI job which checks the formatting. In case there is a formatting failure, the job fails and a suggested diff is output which can be applied with git apply.

The suggestion is:
- add a .clang-format file, (perhaps the one in the fuzzer subdir)
- add a CI job
- add a reformatting commit
- add a .git-blame-ignore-revs  file containing the reformatting commit

**Comment by lemire** [comment]
Sure. E.g., we could adopt the following:

https://github.com/search?q=repo%3Afastfloat%2Ffast_float+clang-format&type=code

My key objection against clang-format in general is that it is clang version dependent. So you must required a fixed version of clang-format. Thankfully, this can be done with docker.

Pull request invited.
