### ISSUE TITLE
Unit test failures on armv7 FreeBSD 15-CURRENT

### ISSUE THREAD

**Issue by clausecker** [simdutf/simdutf#581]
Some of the unit tests fail on armv7 FreeBSD 15-CURRENT.  They seem to have already failed with 5.5.0:

```
92% tests passed, 6 tests failed out of 77

Total Test time (real) =  79.30 sec

The following tests FAILED:
	 22 - validate_utf16le_with_errors_tests (Failed)
	 23 - validate_utf16be_with_errors_tests (Failed)
	 50 - convert_utf16le_to_utf8_with_errors_tests (Failed)
	 51 - convert_utf16be_to_utf8_with_errors_tests (Failed)
	 68 - convert_utf16le_to_utf32_with_errors_tests (Failed)
	 69 - convert_utf16be_to_utf32_with_errors_tests (Failed)
Errors while running CTest
Output from these tests are in: /usr/home/ports/main.ports/converters/simdutf/work/.build/Testing/Temporary/LastTest.log
```

The log file [LastTest.log](https://github.com/user-attachments/files/17345817/LastTest.log) is attached.

**Comment by lemire** [comment]
Hmmm... we do test under arm7:
https://github.com/simdutf/simdutf/blob/master/.github/workflows/armv7.yml

At a glance, all the tests seem to have to do with utf16 as a starting point *and* 'with errors' routines.

The validate functions are surely the simplest. The armv7 system will use the fallback kernel...


https://github.com/simdutf/simdutf/blob/2e9582f8ed3218773675b3540e34eb1726f97d3e/src/fallback/implementation.cpp#L96


So this calls `scalar::utf16::validate_with_errors`.

https://github.com/simdutf/simdutf/blob/2e9582f8ed3218773675b3540e34eb1726f97d3e/src/scalar/utf16.h#L44-L71


Can you see what might be wrong with it?

**Comment by lemire** [comment]
If your system is configured to be a big endian system, we might be missing it... but we try our best...

https://github.com/simdutf/simdutf/blob/2e9582f8ed3218773675b3540e34eb1726f97d3e/include/simdutf/portability.h#L14C1-L52C1

Note that we do run tests in a BE system.

**Comment by clausecker** [comment]
I'll do some analysis and let you know what I find.

**Comment by lemire** [comment]
Thanks!

**Comment by lemire** [comment]
@clausecker If there is a bug, it is fairly likely to be one specific issue given which functions fail (UTF-16 + with error).

**Comment by clausecker** [comment]
The tests seem to fail only if I build them using the FreeBSD ports infrastructure.  If I build the project naturally, it builds fine.  Here is a sample compiler invocation; do you notice anything suspect?

```
/usr/bin/c++ -Dsimdutf_EXPORTS -I/usr/home/ports/main.ports/converters/simdutf/work/simdutf-5.6.0/src -I/usr/home/ports/main.ports/converters/simdutf/work/simdutf-5.6.0/include -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing  -DLIBICONV_PLUG -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing  -DLIBICONV_PLUG  -DNDEBUG -std=c++11 -fPIC -Wall -Wextra -Weffc++ -Wfatal-errors -Wsign-compare -Wshadow -Wwrite-strings -Wpointer-arith -Winit-self -Wconversion -Wno-sign-conversion -Wunused-function -MD -MT src/CMakeFiles/simdutf.dir/simdutf.cpp.o -MF src/CMakeFiles/simdutf.dir/simdutf.cpp.o.d -o src/CMakeFiles/simdutf.dir/simdutf.cpp.o -c /usr/home/ports/main.ports/converters/simdutf/work/simdutf-5.6.0/src/simdutf.cpp
```

**Comment by lemire** [comment]
@clausecker There is a bunch of `-W...` which we can safely ignore.

I am not sure how setting it to *no* strict aliasing could ever lead to a misbehavior? My interpretation is that it could lead to lower performance, but not misbehaviour.

The stack protector flag is not something we use or test with. (Maybe we should.)


Robert: one thing to consider is that the issue may not be with our library per se, but rather with the way the tests are written. Maybe there is something flacky in our tests?

**Comment by clausecker** [comment]
It could be, but I'm not sure what it is.  I'll investigate further and will let you know if I find anything.

**Comment by clausecker** [comment]
More failures: [LastTest.log](https://github.com/user-attachments/files/18238411/LastTest.log).

I found that the errors reproduce when I build manually, but only if I compile with `-fstack-protector-strong -fno-strict-aliasing` as is the case in the ports tree.  Seems like there may be some memory errors.

The failing tests are:

```
	 22 - validate_utf16le_with_errors_tests (Failed)
	 23 - validate_utf16be_with_errors_tests (Failed)
	 50 - convert_utf16le_to_utf8_with_errors_tests (Failed)
	 51 - convert_utf16be_to_utf8_with_errors_tests (Failed)
	 68 - convert_utf16le_to_utf32_with_errors_tests (Failed)
	 69 - convert_utf16be_to_utf32_with_errors_tests (Failed)
```

**Comment by lemire** [comment]
@clausecker The UTF-16 validation function is as follows:

```C++
template <endianness big_endian>
inline simdutf_warn_unused bool validate(const char16_t *buf,
                                         size_t len) noexcept {
  const uint16_t *data = reinterpret_cast<const uint16_t *>(buf);
  uint64_t pos = 0;
  while (pos < len) {
    uint16_t word =
        !match_system(big_endian) ? swap_bytes(data[pos]) : data[pos];
    if ((word & 0xF800) == 0xD800) {
      if (pos + 1 >= len) {
        return false;
      }
      uint16_t diff = uint16_t(word - 0xD800);
      if (diff > 0x3FF) {
        return false;
      }
      uint16_t next_word =
          !match_system(big_endian) ? swap_bytes(data[pos + 1]) : data[pos + 1];
      uint16_t diff2 = uint16_t(next_word - 0xDC00);
      if (diff2 > 0x3FF) {
        return false;
      }
      pos += 2;
    } else {
      pos++;
    }
  }
  return true;
}
```

**Comment by lemire** [comment]
In all you failed tests, the validation-with-error routine returns a location of zero.

**Comment by lemire** [comment]
@clausecker 

We do not test under FreeBSD, but I have added the flags you suggested to our ARM CI:
https://github.com/simdutf/simdutf/pull/614

No luck reproducing the issue.

**Comment by lemire** [comment]
Note that it is possible for our tests to be non-portable. That is, our library might be actually correct despite a failing tests.

**Comment by clausecker** [comment]
The `reinterpret_cast` is technically a strict-aliasing violation, it would be correct to instead cast the dereferenced values.

Note that we test with clang on FreeBSD.  Does your CI run clang, too?

**Comment by pauldreik** [comment]
We test with clang. I tried to reproduce on a raspberry pi (but it runs aarch64) with the same flags you provided, no luck.

I tried to get freebsd running by using https://bentsukun.ch/posts/freebsd-arm-qemu/ but failed (it hangs with 100% cpu before I even see anything related to efi or boot).
Maybe you have some insight on how to get a test system up and running with arm7 and freebsd?

**Comment by clausecker** [comment]
Thank you for attempting to reproduce this.

FreeBSD runs fine on Raspbbery Pi 4, if you have one.  You can set up an armv7 jail on an aarch64 host to test the armv7 build.  I can also give you an account on my machine if you would like to test yourself.

**Comment by pauldreik** [comment]
I run debian bookworm on my rpi 4. Is it possible to setup such a jail on there, and could you provide a pointer on how to do it? I have no experience at all with bsd.
 
Otherwise, it would work a login. I sent you an email!

**Comment by lemire** [comment]
We can remove the unnecessary casts.

https://github.com/simdutf/simdutf/pull/617

Anyhow, technically, char16_t could be a 64-bit type, which would evidently break several functions.

**Comment by pauldreik** [comment]
@clausecker : pauldreik is a good login name, and here is the nonce: 4d55a59162f4c0c3

**Comment by lemire** [comment]
The latest release has removed the unnecessary casts. I have no idea whether it changes things for the FreeBSD ports... but it might!!!

**Comment by clausecker** [comment]
Removing the casts has no effect on the test failures.

**Comment by lemire** [comment]
@clausecker This suggest that the issue might be with how the tests are written. 

Well, it is one type of test in particular.

**Comment by pauldreik** [comment]
I have run on the armv7 BSD system. observations so far:

- the target system is little endian
- I can't get the problem to show with gcc (gcc 13 is the latest available)
- `-fstack-protector-strong` is not a problem, it is the `-fno-strict-aliasing` that is needed to provoke the problem
- the problem happens both on clang 15 and 18
- the problem needs optimization to manifest, -Og and greater.
- NDEBUG is not important
- the target system unfortunately lacks support for sanitizers

@clausecker  - I see that clang devel is installed. can you maybe update it to a later version? very recently, a new sanitizer called type sanitizer was merged which might be useful here. also, is it possible to get sanitizer support (asan+ubsan)?

I have stared at the code without any luck (searching for UB), but I at least found some illegal identifiers which I fixed in https://github.com/simdutf/simdutf/pull/621

**Comment by clausecker** [comment]
@pauldreik I've installed llvm-devel-20.0.d20241015 of 2024-10-15.  If this is not recent enough, I have started to compile one of 2024-12-15.

**Comment by pauldreik** [comment]
Unfortunately no luck with the new llvm, it is unfortunately not recent enough. It must contain this commit from 20241217: https://github.com/llvm/llvm-project/commit/a487b792e2dabcec02c63d19e32958572a257408 

But, I made an interesting observation: adding a printf reading the utf16 variable makes the test pass:
```cpp
#if SIMDUTF_IS_BIG_ENDIAN
// todo: port this test for big-endian platforms.
#else
TEST(
    validate_utf16le_with_errors_returns_error_when_input_has_wrong_second_word_value) {
  uint32_t seed{1234};
  simdutf::tests::helpers::random_utf16 generator{seed, 1, 0};
  auto utf16{generator.generate(128)};
  const char16_t *buf = reinterpret_cast<const char16_t *>(utf16.data());
  const size_t len = utf16.size();

  const std::array<char16_t, 5> sample_wrong_second_word{0x0000, 0x1000, 0xdbff,
                                                         0xe000, 0xffff};

  const char16_t valid_surrogate_W1 = 0xd800;
  for (char16_t W2 : sample_wrong_second_word) {
    for (size_t i = 0; i < utf16.size() - 1; i++) {
      const char16_t old_W1 = utf16[i + 0];
      const char16_t old_W2 = utf16[i + 1];

      utf16[i + 0] = valid_surrogate_W1;
      utf16[i + 1] = W2;

      simdutf::result res = implementation.validate_utf16le_with_errors(
          reinterpret_cast<const char16_t *>(buf), len);

      ASSERT_EQUAL(res.error, simdutf::error_code::SURROGATE);
      if (res.count != i) {
        for (int j = 0; j < static_cast<int>(utf16.size()); ++j) {
          std::printf("oops! utf16[%d]=%d\n", j, +utf16.at(j));  // <--------------------here 
        }
      }
      ASSERT_EQUAL(res.count, i);

      utf16[i + 0] = old_W1;
      utf16[i + 1] = old_W2;
    }
  }
}
#endif
```

I tried to reproduce the problem by moving the implementation into the test file, but no luck - the test stops failing when moved.

I have other stuff I want to work with - maybe someone else wants to  have a stab at this issue?

**Comment by pauldreik** [comment]
there is a reproducer branch here where I have made partial success for minimizing: https://github.com/simdutf/simdutf/tree/reproduce_bsd_error

**Comment by lemire** [comment]
I'll patch this test to try to help.

**Comment by lemire** [comment]
I think that the casts are unnecessary, we can remove them. Even so, that's unlikely to be the source of the problem. But let us remove them anyhow.

**Comment by lemire** [comment]
We can use freebsd as a VM in our CI tests... https://github.com/vmactions/freebsd-vm

**Comment by pauldreik** [comment]
> We can use freebsd as a VM in our CI tests... https://github.com/vmactions/freebsd-vm

that looks a good thing to add, regardless of this issue. The problem in this issue is however only reproducible in the armv7I jail, not in the aarch64 "parent".   That might be possible in the future: https://github.com/vmactions/freebsd-vm?tab=readme-ov-file#upcoming-features

**Comment by pauldreik** [comment]
I have now reduced it to the following:

Makefile:
```Makefile
CXX:=clang++
CXXFLAGS:=-Og -fno-strict-aliasing
main: main.o code.o
	$(CXX) -o $@ main.o code.o
main.o: main.cpp Makefile
        $(CXX) $(CXXFLAGS) -c $< -o $@
code.o: code.cpp Makefile
        $(CXX) $(CXXFLAGS) -c $< -o $@
clean:
      	rm -rf main.o code.o main
```

 main.cpp:
```c++
#include <cstdio>
#include <vector>
#include <cstdlib>

std::vector<char16_t> get_test_data();
std::size_t validate_utf16le_with_errors(const char16_t *buf, std::size_t len);

int main(int argc, char *argv[]) {
  auto utf16 = get_test_data();

  const char16_t valid_surrogate_W1 = 0xd800;
  const char16_t W2 = 0;
  for (size_t i = 0; i < utf16.size() - 1; i++) {
    const char16_t old_W1 = utf16[i + 0];
    const char16_t old_W2 = utf16[i + 1];

    utf16[i + 0] = valid_surrogate_W1;
    utf16[i + 1] = W2;

    const auto res = validate_utf16le_with_errors(utf16.data(), utf16.size());

    if (res != i) {
      //      #if PRINT_VECTOR                                                                                                                                                                                                                                                                                               
       for (auto u : utf16) {
         std::printf("%d, ", u);
       }
       std::printf("\n");
       //#endif                                                                                                                                                                                                                                                                                                              

      std::printf("FAILED!!\n");
      std::exit(EXIT_FAILURE);
    }

    utf16[i + 0] = old_W1;
    utf16[i + 1] = old_W2;
  }
  std::printf("SUCCESS\n");
  std::exit(EXIT_SUCCESS);
}
```

code.cpp:
```c++
#include <cstdint>
#include <vector>

std::size_t validate_utf16le_with_errors(const char16_t *data, size_t len) {
  size_t pos = 0;
  while (pos < len) {
    char16_t word = data[pos];
    if ((word & 0xF800) == 0xD800) {
      if (pos + 1 >= len) {
        return pos;
      }
      char16_t diff = char16_t(word - 0xD800);
      if (diff > 0x3FF) {
        return pos;
      }
      char16_t next_word = data[pos + 1];
      char16_t diff2 = uint16_t(next_word - 0xDC00);
      if (diff2 > 0x3FF) {
        return pos;
      }
      pos += 2;
    } else {
      pos++;
    }
  }
  return pos;
}

std::vector<char16_t> get_test_data() { return {34086, 23924, 65167}; }
```

`make && ./main `
should print SUCCESS, while on BSD armv7 it prints FAILED

It seems like this has nothing to do with simdutf, but rather some kind of compiler bug.

**Comment by pauldreik** [comment]
I think we should close this. @clausecker maybe you want to file a compiler bug?

**Comment by clausecker** [comment]
Thank you for reducing this test case, I will see that I can file a compiler bug.

**Comment by clausecker** [comment]
I have updated llvm-devel on pi to a version new enough to have the desired commit.  Please check again.

**Comment by pauldreik** [comment]
> I have updated llvm-devel on pi to a version new enough to have the desired commit. Please check again.

I tried,  I get:

> clang++-devel -Og -fno-strict-aliasing -fsanitize=type -c main.cpp -o main.o
> clang++: error: unsupported argument 'type' to option '-fsanitize='

Neither do address or undefined sanitizer work, I get:

> ld: error: cannot open /usr/local/llvm-devel/lib/clang/20/lib/armv7-portbld-freebsd14.1-gnueabihf/libclang_rt.asan_static.a: No such file or directory
> ld: error: cannot open /usr/local/llvm-devel/lib/clang/20/lib/armv7-portbld-freebsd14.1-gnueabihf/libclang_rt.asan.a: No such file or directory
> ld: error: cannot open /usr/local/llvm-devel/lib/clang/20/lib/armv7-portbld-freebsd14.1-gnueabihf/libclang_rt.asan_cxx.a: No such file or directory

**Comment by clausecker** [comment]
Oh yeah, we don't support asan on armv7.  It hasn't been ported yet.

**Comment by lemire** [comment]
@clausecker valgrind?

**Comment by clausecker** [comment]
@lemire Only available on arm64 and amd64 FreeBSD.

**Comment by clausecker** [comment]
The compiler bug has been fixed up stream.

**Comment by lemire** [comment]
@clausecker 

> The compiler bug has been fixed up stream

Do you have a link?

(It would be more interesting if we knew what the bug was!)

**Comment by clausecker** [comment]
It's https://github.com/llvm/llvm-project/issues/121299, there's a link earlier in the thread.
