### ISSUE TITLE
Version Not Updated in CMakeLists File `5.6.2`

### ISSUE THREAD

**Issue by ErniGH** [simdutf/simdutf#588]
Hello, 👋 . I was reviewing this  pull request in Conan Center Index (https://github.com/conan-io/conan-center-index/pull/25967) to add the latest version, and I noticed that in the new `5.6.2`, the version number has not been updated in the CMakeLists file.

See: https://github.com/simdutf/simdutf/blob/v5.6.2/CMakeLists.txt#L6

**Comment by lemire** [comment]
Fixed. Thanks for the report.
