### ISSUE TITLE
Bad performance on shorter strings

### ISSUE THREAD

**Issue by gix** [simdutf/simdutf#590]
I was looking at replacing Windows' conversion routines (`MultiByteToWideChar` etc.) and was a bit surprised how slow simdutf was in comparison (even when using the non-validating functions, while Windows always validates). My test dictionary had strings up to 100 chars in length with mostly ASCII. For example there seems to be no SWAR in certain scalar implementations like counting. Also 32-bit builds only use the fallback implementation, regardless of SSE support. If simdutf really is only intended for large strings some guidance in the documentation would be nice.

**Comment by lemire** [comment]
> Also 32-bit builds only use the fallback implementation, regardless of SSE support.

We are not going to support 32-bit builds with anything but a fallback implementation. At this point, 32-bit builds are legacy. If you want accelerated functions, please use a 64-bit build.

> If simdutf really is only intended for large strings some guidance in the documentation would be nice.

It is not the case. See for example Figure 4 from one of our recent papers:

* [Transcoding Unicode Characters with AVX-512 Instructions](https://arxiv.org/pdf/2212.05098), Software: Practice and Experience 53 (12), 2023.


<img width="1094" alt="Screenshot 2024-11-18 at 9 52 08 AM" src="https://github.com/user-attachments/assets/3937acc2-924e-4a9a-a562-94c8c21abb29">

We have benchmark tools as part of the library which can be used to assess the performance.

If you are encountering bad performance, please provide a reproducible test case. E.g., provide the data and the function you are using. Please describe your system (processors, compiler, etc.).


> For example there seems to be no SWAR in certain scalar implementations like counting.

We welcome pull requests if you find that some routines can be improved. The simdutf library is a community driven project.


---

I am going to close this issue. The reporter is encouraged to open a new issue with a reproducible test case.

**Comment by lemire** [comment]
We explicitly document that we expect 64-bit systems:

<img width="890" alt="Screenshot 2024-11-18 at 11 16 16 AM" src="https://github.com/user-attachments/assets/2e421c01-226d-4819-9546-6058207d707a">


If you are working on 32-bit systems, the simdutf library might not be a good choice.
