### ISSUE TITLE
oss-fuzz build error

### ISSUE THREAD

**Issue by lemire** [simdutf/simdutf#594]
We have a report that our oss-fuzz builds fail.

Here is the log:

https://oss-fuzz-build-logs.storage.googleapis.com/log-16c9cd89-346f-4d55-8ccd-bce7e146f834.txt

**Comment by lemire** [comment]
@pauldreik Do you understand the error?

**Comment by pauldreik** [comment]
looks like some failure related to building for arm. we are not alone: https://github.com/google/oss-fuzz/issues/12670 

I think we should disable aarch64 since the support is non-official and not working (non-official but working had been fine). that has to be done via an oss-fuzz PR.

**Comment by pauldreik** [comment]
https://github.com/google/oss-fuzz/pull/12758

**Comment by lemire** [comment]
Thanks!

**Comment by lemire** [comment]
Now the problem is identified, let us close this.
