### ISSUE TITLE
Different outputs are generated by convert_valid_utf8_to_latin1+fallback and convert_valid_utf8_to_latin1+rvv

### ISSUE THREAD

**Issue by txwhqq** [simdutf/simdutf#610]
I have run the benchmarks and specified the input as emoji.txt and found that Different outputs were generated by the convert_valid_utf8_to_latin1+fallback and the convert_valid_utf8_to_latin1+rvv.
The first four input elements and the first four output elements are printed , and the results are showed as below:
![image](https://github.com/user-attachments/assets/4466b2f8-a8b1-4e34-a278-bb48b2b53239)
![image](https://github.com/user-attachments/assets/040e4e09-6fa1-430e-bcb8-ca471422a825)

The return value of convert_valid_utf8_to_latin1+fallback is zero and an error message of "The output is zero which might indicate an error." are reported (showed as below), but the return value of the convert_valid_utf8_to_latin1+rvv is not zero and it will not report this messge.
![image](https://github.com/user-attachments/assets/a7089ddb-42e6-4fb5-b784-165116755b15)

**Comment by lemire** [comment]
The `convert_valid_*` should only be used on valid UTF-8 sequences. It is your responsability to ensure that the inputs are valid.

Most users should *NOT* use these functions. You should use the validating functions.

I am closing this issue.
