### ISSUE TITLE
Base64 decode inconsistency for input with/without spaces

### ISSUE THREAD

**Issue by tantei3** [simdutf/simdutf#619]
As briefly discussed in #615, and as per the tests added in #618, there is inconsistency in the return values for the base64 decode functions. For the string "    ==" with spaces at the beginnning, using `strict` and `stop_before_partial` results in `BASE64_INPUT_REMAINDER` and `SUCCESS`, whereas for the string "==" without spaces (or trailing spaces), the error returned is `INVALID_BASE64_CHARACTER` in all cases, which seems inconsistent given that spaces are ignored and should not affect the result.

This issue is created to investigate this behavior.

**Comment by tantei3** [comment]
@lemire can you confirm if this is a bug or if this is expected and documented behavior?

**Comment by lemire** [comment]
@tantei3 I am not sure but we can change the behaviour. I would invite a pull request with updated tests and updated behaviour.

**Comment by lemire** [comment]
Closing by PR https://github.com/simdutf/simdutf/pull/620
