### ISSUE TITLE
Transcoding to UTF-32

### ISSUE THREAD

**Issue by lemire** [simdutf/simdutf#76]
We might want to implement transcoding to (and from?) UTF-32.

Related issue: https://github.com/simdjson/simdjson/issues/1682

**Comment by lemire** [comment]
cc @kostya

**Comment by WojciechMula** [comment]
Transcoding from UTF-8 & UTF-16 to UTF-32 seems relative easy.

**Comment by lemire** [comment]
@WojciechMula Indeed. It should be easier than what we already offer. And faster...
