### ISSUE TITLE
Wrong version in simdutf_version.h

### ISSUE THREAD

**Issue by lpinca** [simdutf/simdutf#78]
The latest tag is v1.0.0 but the version in [`simdutf_version.h`](https://github.com/simdutf/simdutf/blob/v1.0.0/include/simdutf/simdutf_version.h) is 0.1.0.

A comment in `simdutf_version.h` says that the version should not be changed by hand but it seems the `release.py` script is also missing.

**Comment by lemire** [comment]
Thanks for the report. Fixed.

**Comment by lpinca** [comment]
It seems this one https://github.com/simdutf/simdutf/blob/d1bef814dc4331bb8d06a40ee84f966c43650661/include/simdutf/simdutf_version.h#L7 is still incorrect.
