### ISSUE TITLE
Dependency to libICU should be optional

### ISSUE THREAD

**Issue by WojciechMula** [simdutf/simdutf#84]
Didn't dig into the benchmarks' details, but I believe me may conditionally compile parts requiring ICU.

**Comment by lemire** [comment]
@WojciechMula I think that it is currently optional in the sense that it should still build even if ICU is missing.

Of course, it would be nicer to build it as a CMake dependency, say.

(Be mindful that we want to be as portable as possible.)

**Comment by lemire** [comment]
Also, of course, it is only required for benchmarking.

**Comment by WojciechMula** [comment]
Unfortunately, the lib does not build if ICU is missing. I'll look at this in my spare time.

**Comment by lemire** [comment]
That's a bug because we do have the checks in place...

https://github.com/simdutf/simdutf/blob/98915f842b8e5aa448b9b8767ecd1e70fad2d2df/benchmarks/src/benchmark.h#L58

**Comment by WojciechMula** [comment]
Sorry, it was my mistake. Cmake reported an error, but I didn't notice that I pasted some garbage into the cmd line. The actual error wasn't related to ICU.
