### ISSUE TITLE
Make atomic_ptr optional for active_implementation?

### ISSUE THREAD

**Issue by TerrorJack** [simdutf/simdutf#90]
When cross-compiling `simdutf` targetting `wasm32-wasi`, due to lack of `<atomics>` and such, compilation will fail. Would you accept a patch that opt out of `atomic_ptr` on platforms that lack threads and atomics?

**Comment by lemire** [comment]
I don’t see how you can use simdutf without runtime dispatching. The implementations are system specific.

How would that work? How does the aarch64 implementation/kernel kicks in if you do not detect it?

**Comment by TerrorJack** [comment]
Ah, I really mean using a regular pointer for runtime dispatching instead of using an atomic, sorry for the confusion.

**Comment by lemire** [comment]
@TerrorJack We use an atomic to ensure thread safety. We are open to changing this code, but one needs to prove that thread safety is maintained.

Honestly, a C++ platform that does not support atomics does not seem like a serious platform. Are you sure it is not supported?

**Comment by TerrorJack** [comment]
> We are open to changing this code, but one needs to prove that thread safety is maintained.

Platforms that do support `atomic` will continue to use it by default.

> Honestly, a C++ platform that does not support atomics does not seem like a serious platform. Are you sure it is not supported?

I'm sure `wasm32-wasi` doesn't have threads or atomics at the moment. The bundled `libc` does not have `pthread`, and the bundled `libc++` does not ship anything threading related. And it is a serious platform! (well, at least serious enough for me to get paid.)

**Comment by WojciechMula** [comment]
Daniel, since the standard allows `std::hardware_concurrency` to return 0, I wouldn't be worried about thread safety. ;)

I'd be happy if we end up with some macro definition that explicitly enables the use of bare pointers. However, by default we should assume `<atomic>` is there.

**Comment by WojciechMula** [comment]
@TerrorJack It would nicer if we ended up with the following code:

```cpp
#ifdef SIMDUTF_HAS_ATOMIC
template <typename T>
using simdutf::atomic = std::atomic;
#else
template <typaneme T>
using simdutf::atomic = dummy::atomic;
#endif
```

Where `dummy::atomic` is a template providing the methods from `std::atomic` we actually use.

**Comment by WojciechMula** [comment]
@TerrorJack technically your solution is fine. However, there are too many `ifdefs` --- five. :) There should be exactly one place in the code where we use an `ifdef`. Please rethink your approach. It'd be fine if we introduce a new header file for atomics.
