### ISSUE TITLE
Out of bounds writes in Haswell UTF16 to UTF-8 conversion

### ISSUE THREAD

**Issue by sneves** [simdutf/simdutf#92]
For example, the hex-encoded UTF-16LE string

```
690069004106ff00680041006800690069084106ff006800410068006900690069004106ff0068004100680069004100
```

results in an out of bounds write when using `utf8_length_from_utf16` to calculate the output size.

I have not investigated the root cause too deeply, but adjusting the [safety factor](https://github.com/simdutf/simdutf/blob/master/src/haswell/avx2_convert_utf16_to_utf8.cpp#L61) from 8 to (at least) 11 seems to eliminate the out of bounds writes.

**Comment by lemire** [comment]
Thanks for the bug report. I will investigate.

**Comment by sneves** [comment]
A simpler case might be `u"崀T0dTTsTsdTTTsTTsdTTsTTs"` = `005d54003000640054005400730054007300640054005400540073005400540073006400540054007300540054007300`, which contains a single non-ASCII character at the beginning.

The first 32-byte, 16-character block, enters the `if (surrogates_bitmask == 0x00000000)` branch, and each of the four writes at the end are at offsets 0, 6, 10, 14. Because 14+16 = 30 > 26, the last write goes out of bounds. However, `buf + 16 + 8 <= end`, which in terms of offsets becomes `16+8 <= 24` is true.

**Comment by lemire** [comment]
Patch release issued.
